// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	"github.com/go-openapi/spec"
	"k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/epmd-edp/go-go-operator-sdk-postgresql/pkg/apis/v1/v1alpha1.HelloWorld":             schema_pkg_apis_v1_v1alpha1_HelloWorld(ref),
		"github.com/epmd-edp/go-go-operator-sdk-postgresql/pkg/apis/v1/v1alpha1.HelloWorldStatusSpec":   schema_pkg_apis_v1_v1alpha1_HelloWorldStatusSpec(ref),
		"github.com/epmd-edp/go-go-operator-sdk-postgresql/pkg/apis/v1/v1alpha1.HelloWorldStatusStatus": schema_pkg_apis_v1_v1alpha1_HelloWorldStatusStatus(ref),
	}
}

func schema_pkg_apis_v1_v1alpha1_HelloWorld(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "HelloWorld is the Schema for the helloworld API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/epmd-edp/go-go-operator-sdk-postgresql/pkg/apis/v1/v1alpha1.HelloWorldSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/epmd-edp/go-go-operator-sdk-postgresql/pkg/apis/v1/v1alpha1.HelloWorldStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta", "github.com/epmd-edp/go-go-operator-sdk-postgresql/pkg/apis/v1/v1alpha1.HelloWorldSpec", "github.com/epmd-edp/go-go-operator-sdk/pkg/apis/v1/v1alpha1.HelloWorldStatus"},
	}
}

func schema_pkg_apis_v1_v1alpha1_HelloWorldStatusSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "HelloWorldStatusSpec defines the desired state of helloworldstatus",
				Properties: map[string]spec.Schema{
					"sourceMessage": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
				Required: []string{"sourceMessage"},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_v1_v1alpha1_HelloWorldStatusStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "HelloWorldStatusStatus defines the observed state of HelloWorld",
				Properties: map[string]spec.Schema{
					"targetMessage": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
				Required: []string{"targetMessage"},
			},
		},
		Dependencies: []string{},
	}
}
